source "https://rubygems.org"

gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll", "~> 3.9"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-paginate-content", "~> 1.0"
gem "json"
gem "jekflix"
